language: rust
rust:
  - nightly
cache:
  cargo: true
matrix:
  include:
    - os: osx # 10.12
      env: CGFEATURES="--features elcapitan"
    - os: osx # 10.10
      osx_image: xcode7.2
      env: CGFEATURES=""
    - os: osx # 10.13
      osx_image: xcode9.4
      env: CGFEATURES="--features highsierra,elcapitan"
before_script:
  - rustup component add clippy-preview rustfmt-preview
script:
  - cargo build
  - cargo test --verbose -- --nocapture
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
