branches:
  only:
  - master
language: rust
rust:
  - stable
cache:
  cargo: true
matrix:
  include:
    # https://docs.travis-ci.com/user/reference/osx/#os-x-version
    - os: osx # 10.14
      osx_image: xcode11.3
    - os: osx # 10.13
      osx_image: xcode10.1
    - os: osx # 10.12
      osx_image: xcode9.2
before_install:
  - rustup component add clippy rustfmt
script:
  - cargo build
  - cargo test --verbose -- --nocapture
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
