branches:
  only:
  - master
language: rust
rust:
  - nightly
cache:
  cargo: true
matrix:
  include:
    # https://docs.travis-ci.com/user/reference/osx/#os-x-version
    - os: osx # 10.13
      osx_image: xcode10
    - os: osx # 10.13
      osx_image: xcode9.4
before_install:
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  - rustup component add rustfmt || cargo install --git https://github.com/rust-lang/rustfmt/ --force rustfmt
script:
  - cargo build
  - cargo test --verbose -- --nocapture
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
