[package]
authors = ["Dylan Frankland <github@frankland.io>"]
name = "xpc-connection"
version = "0.1.0"
edition = "2018"

[build-dependencies]
bindgen = "0.40.0"

[dependencies]
block = "0.1.6"

[dev-dependencies]
crossbeam-deque = "0.6.1"
